uav0_parameters:
    adj: [0, 0, 0, 0]
    b: 1
    d: 0
    m: 0.722
    pos0: [1.0, 0., 1.0]
    offset: [0., 0., 0.]
    dt: 0.01
    group: '/uav0'

uav0_fntsmc_parameters:
    # 单机飞定点 加200g砝码，风扇
    # k1: [0.3, 0.3, 0.3]
    # k2: [0.5, 0.5, 0.5]
    # k3: [1.5, 1.5, 1.5]
    # k4: [6, 6, 6]
    # alpha1: [1.01, 1.01, 1.01]
    # alpha2: [1.01, 1.01, 1.01]
    # k_yyf_i: [0.00, 0.00, 0.00]
    # k_yyf_d: [0., 0., 0.]
    # k_yyf_p: [0., 0., 0.0]
    # k_com_pos: [0.05, 0.05, -0.08]
    # k_com_vel: [0.05, 0.05, 0.1]
    # k_com_acc: [0.0, 0.0, 0.0]

    # 单机飞圆，不加砝码
#    k1: [0.3, 0.3, 0.3]
#    k2: [0.5, 0.5, 0.5]
#    k3: [0.5, 0.5, 0.5]
#    k4: [3, 3, 3]
#    alpha1: [1.01, 1.01, 1.01]
#    alpha2: [1.01, 1.01, 1.01]
#    k_yyf_i: [0.002, 0.002, 0.001]
#    k_yyf_d: [0.15, 0.15, 0.10]
#    k_yyf_p: [0.1, 0.1, 0.06]
#    k_com_pos: [0.05, 0.05, -0.1]
#    k_com_vel: [0.05, 0.05, -0.1]
#    k_com_acc: [0.0, 0.0, 0.0]

    # 单飞机圆, 加 200g 砝码，consensus
    # k1: [0.3, 0.3, 0.3]
    # k2: [0.5, 0.5, 0.5]
    # k3: [0.5, 0.5, 1.5]
    # k4: [6, 4, 8]
    # alpha1: [1.01, 1.01, 1.01]
    # alpha2: [1.01, 1.01, 1.01]
    # k_yyf_i: [0.00, 0.00, 0.00]
    # k_yyf_d: [0., 0., 0.]
    # k_yyf_p: [0., 0., 0.]
    # k_com_pos: [0.05, 0., 0.2]
    # k_com_vel: [0.1, 0.1, 0.1]
    # k_com_acc: [0., 0., 0.0]
    # k_yyf_i: [0.002, 0.002, 0.001]
    # k_yyf_d: [0.15, 0.15, 0.2]
    # k_yyf_p: [0.1, 0.1, 0.1]
    # k_com_pos: [0.05, 0.1, -0.1]
    # k_com_vel: [0.05, 0.1, 0.0]
    # k_com_acc: [0.1, 0.1, -0.2]

    # 强化学习飞圆，加 200g 砝码，consensus (因为控制参数要被刷新，所以有一些缺省)
    k1: [0.3, 0.3, 0.3]
    k2: [0.5, 0.5, 0.5]
    k3: [0.5, 0.5, 1.5]
    k4: [6, 4, 8]
    alpha1: [1.01, 1.01, 1.01]
    alpha2: [1.01, 1.01, 1.01]
    k_yyf_i: [0.00, 0.00, 0.00]
    k_yyf_d: [0., 0., 0.]
    k_yyf_p: [0., 0., 0.]
    k_com_pos: [0.5, 0.3, -0.03]
    k_com_vel: [0.1, 0.12, 0.]
    k_com_acc: [0.7, 0.05, 0.0]     # 挺好，可以继续增大加速度补偿
    dim: 3
    dt: 0.01

uav0_rfntsmc_parameters:
    k1: [1.2, 0.8, 1.5]
    k2: [0.2, 0.6, 1.5]
    alpha: [1.2, 1.5, 1.2]
    beta: [0.3, 0.3, 0.3]
    gamma: [0.2, 0.2, 0.2]
    lmd: [2.0, 2.0, 2.0]
    k_yyf_i: [0.00, 0.00, 0.00]
    k_yyf_d: [0., 0., 0.]
    k_yyf_p: [0., 0., 0.0]
    k_com_pos: [0.0, 0.0, -0.0]
    k_com_vel: [0.0, 0.0, 0.]
    k_com_acc: [0.0, 0.0, 0.0]
    dim: 3
    dt: 0.01

uav0_obs_xy:
    use_freq: True
    omega: [[1.0, 1.1, 1.2], [1.0, 1.1, 1.2]]
    dim: 2
    dt: 0.01

uav0_obs_z:
    use_freq: True
    omega: [[1.2, 1.2, 1.2]]
    dim: 1
    dt: 0.01
