uav2_parameters:
    adj: [0, 0, 0, 0]
    b: 1
    d: 0
    m: 0.850
    pos0: [1.5, -1.5, 0.5]
    offset: [0., 0., 0.]
    dt: 0.01
    group: '/uav2'

uav2_fntsmc_parameters:
    # 单机飞定点 加200g砝码，风扇
    # k1: [0.3, 0.3, 0.3]
    # k2: [0.5, 0.5, 0.5]
    # k3: [1.5, 1.5, 1.5]
    # k4: [6, 6, 6]
    # alpha1: [1.01, 1.01, 1.01]
    # alpha2: [1.01, 1.01, 1.01]
    # k_yyf_i: [0.00, 0.00, 0.00]
    # k_yyf_d: [0., 0., 0.]
    # k_yyf_p: [0., 0., 0.0]
    # k_com_pos: [0.05, 0.05, -0.08]
    # k_com_vel: [0.05, 0.05, 0.1]
    # k_com_acc: [0.0, 0.0, 0.0]

    # 单机飞圆，不加砝码
    k1: [0.3, 0.3, 0.3]
    k2: [0.5, 0.5, 0.5]
    k3: [0.5, 0.5, 0.5]
    k4: [1, 1, 1]
    alpha1: [1.01, 1.01, 1.01]
    alpha2: [1.01, 1.01, 1.01]
    k_yyf_i: [0.002, 0.002, 0.001]
    k_yyf_d: [0.15, 0.15, 0.10]
    k_yyf_p: [0.1, 0.1, 0.06]
    k_com_pos: [0.05, 0.05, -0.1]
    k_com_vel: [0.05, 0.05, -0.1]
    k_com_acc: [0.0, 0.0, 0.0]

    # 单飞机圆, 加 200g 砝码
#    k1: [0.3, 0.3, 0.3]
#    k2: [0.5, 0.5, 0.5]
#    k3: [0.5, 0.5, 1.5]
#    k4: [3, 3, 8]
#    alpha1: [1.01, 1.01, 1.01]
#    alpha2: [1.01, 1.01, 1.01]
#    k_yyf_i: [0.002, 0.002, 0.001]
#    k_yyf_d: [0.15, 0.15, 0.2]
#    k_yyf_p: [0.1, 0.1, 0.1]
#    k_com_pos: [0.05, 0.1, -0.1]
#    k_com_vel: [0.05, 0.1, 0.0]
#    k_com_acc: [0.1, 0.1, -0.2]
    dim: 3
    dt: 0.01


uav2_rfntsmc_parameters:
    k1: [1.2, 0.8, 1.5]
    k2: [0.2, 0.6, 1.5]
    alpha: [1.2, 1.5, 1.2]
    beta: [0.3, 0.3, 0.3]
    gamma: [0.2, 0.2, 0.2]
    lmd: [2.0, 2.0, 2.0]
    k_yyf_i: [0.00, 0.00, 0.00]
    k_yyf_d: [0., 0., 0.]
    k_yyf_p: [0., 0., 0.0]
    k_com_pos: [0.0, 0.0, -0.0]
    k_com_vel: [0.0, 0.0, 0.]
    k_com_acc: [0.0, 0.0, 0.0]
    dim: 3
    dt: 0.01


# uav2_pdt_fntsmc_parameters:
#     alpha_s: [ 0.66667, 0.66667, 0.66667 ]
#     beta1_s: [ 2, 2, 2 ]
#     beta2_s: [ 2., 2., 2. ]
#     beta3_s: [ 2., 2., 2. ]
#     Ts: [20., 20., 20.]
#     kappa1_s: [0.9, 0.9, 1.]

#     alpha_c: [ 0.66667, 0.66667, 0.66667]
#     beta1_c: [ 2, 2, 2 ]
#     beta2_c: [ 2., 2., 2. ]
#     beta3_c: [ 2., 2., 2. ]
#     Tc: [ 30., 30., 30. ]
#     kappa1_c: [0.9, 0.9, 1.]

#     k2: [1., 1., 1.0]

#     k_yyf_i: [0.0, 0.0, 0.0]
#     k_yyf_d: [0., 0., 0.]
#     k_yyf_p: [0., 0., 0.0]
#     k_com_pos: [0.0, 0.0, 0.0]
#     k_com_vel: [0.0, 0.0, 0.]
#     k_com_acc: [0.3, 0.3, 0.3]

#     dim: 3
#     dt: 0.01

# 圆实验好的数据
# uav2_pdt_fntsmc_parameters:
#     alpha_s: [ 0.66667, 0.66667, 0.66667 ]
#     beta1_s: [ 6, 6, 10 ]
#     beta2_s: [ 3., 3., 3. ]
#     beta3_s: [ 3., 3., 3. ]
#     Ts: [10., 10., 10.]
#     kappa1_s: [0.9, 0.9, 1.]

#     alpha_c: [ 0.66667, 0.66667, 0.66667]
#     beta1_c: [ 6, 6, 10 ]
#     beta2_c: [ 3., 3., 3. ]
#     beta3_c: [ 3., 3., 3. ]
#     Tc: [ 10., 10., 10. ]
#     kappa1_c: [0.9, 0.9, 1.]

#     k2: [1., 1., 3.0]

#     k_yyf_i: [0.0, 0.0, 0.0]
#     k_yyf_d: [0., 0., 0.]
#     k_yyf_p: [0., 0., 0.0]
#     k_com_pos: [0.0, 0.0, 0.0]
#     k_com_vel: [0.0, 0.0, 0.]
#     k_com_acc: [0.3, 0.3, 0.3]

#     dim: 3
#     dt: 0.01

# 8实验好的数据
uav2_pdt_fntsmc_parameters:
    alpha_s: [ 0.66667, 0.66667, 0.66667 ]
    beta1_s: [ 5, 5, 5 ]
    beta2_s: [ 3., 3., 3. ]
    beta3_s: [ 3., 3., 3. ]
    Ts: [10., 10., 10.]
    kappa1_s: [0.9, 0.9, 1.]

    alpha_c: [ 0.66667, 0.66667, 0.66667]
    beta1_c: [ 3, 3, 10 ]
    beta2_c: [ 3., 3., 3. ]
    beta3_c: [ 3., 3., 3. ]
    Tc: [ 10., 10., 10. ]
    kappa1_c: [0.9, 0.9, 1.]

    k2: [1.2, 1.2, 2.0]

    k_yyf_i: [0.0, 0.001, 0.005]
    k_yyf_d: [0., 0., 0.]
    k_yyf_p: [0., 0., 0.0]
    k_com_pos: [0.0, 0.0, 0.0]
    k_com_vel: [0.0, 0.0, 0.]
    k_com_acc: [-1.0, -1.0, 0.]

    dim: 3
    dt: 0.01

uav2_pdt_do:
    T0: [1, 1, 1]
    k1: [1, 1, 1]
    alpha: [0.66667, 0.66667, 0.66667]
    beta1: [2.828, 2.828, 2.828]
    beta2: [2, 2, 2]
    beta3: [2, 2, 2]
    dim: 3
    dt: 0.01

uav2_obs_xy:
    use_freq: True
    omega: [[1.0, 1.1, 1.2], [1.0, 1.1, 1.2]]
    dim: 2
    dt: 0.01

uav2_obs_z:
    use_freq: True
    omega: [[1.2, 1.2, 1.2]]
    dim: 1
    dt: 0.01
