uav2_parameters:
    adj: [1, 0, 0, 0]
    b: 0
    d: 1
    m: 0.722
    pos0: [1.5, 1.5, 0.5]
    offset: [0., 0., 0.]
    dt: 0.01
    group: '/uav2'

uav2_fntsmc_parameters:
    # 单机飞定点 加200g砝码，风扇
    k1: [0.3, 0.3, 0.3]
    k2: [0.5, 0.5, 0.5]
    k3: [1.5, 1.5, 1.5]
    k4: [6, 6, 6]
    alpha1: [1.01, 1.01, 1.01]
    alpha2: [1.01, 1.01, 1.01]
    k_yyf_i: [0.00, 0.00, 0.00]
    k_yyf_d: [0., 0., 0.]
    k_yyf_p: [0., 0., 0.0]
    k_com_pos: [0.05, 0.05, -0.08]
    k_com_vel: [0.05, 0.05, 0.1]
    k_com_acc: [0.0, 0.0, 0.0]

    # 单机飞圆，不加砝码
#    k1: [0.3, 0.3, 0.3]
#    k2: [0.5, 0.5, 0.5]
#    k3: [0.5, 0.5, 0.5]
#    k4: [3, 3, 3]
#    alpha1: [1.01, 1.01, 1.01]
#    alpha2: [1.01, 1.01, 1.01]
#    k_yyf_i: [0.002, 0.002, 0.001]
#    k_yyf_d: [0.15, 0.15, 0.10]
#    k_yyf_p: [0.1, 0.1, 0.06]
#    k_com_pos: [0.05, 0.05, -0.1]
#    k_com_vel: [0.05, 0.05, -0.1]
#    k_com_acc: [0.0, 0.0, 0.0]

    # 单飞机圆, 加 200g 砝码
#    k1: [0.3, 0.3, 0.3]
#    k2: [0.5, 0.5, 0.5]
#    k3: [0.5, 0.5, 1.5]
#    k4: [3, 3, 8]
#    alpha1: [1.01, 1.01, 1.01]
#    alpha2: [1.01, 1.01, 1.01]
#    k_yyf_i: [0.002, 0.002, 0.001]
#    k_yyf_d: [0.15, 0.15, 0.2]
#    k_yyf_p: [0.1, 0.1, 0.1]
#    k_com_pos: [0.05, 0.1, -0.1]
#    k_com_vel: [0.05, 0.1, 0.0]
#    k_com_acc: [0.1, 0.1, -0.2]
    dim: 3
    dt: 0.01

uav2_pdt_fntsmc_parameters:
    alpha_s: [ 0.6, 0.6, 0.6 ]
    beta1_s: [ 3., 3., 3. ]
    beta2_s: [ 1., 1., 1. ]
    beta3_s: [ 1., 1., 1. ]
    Ts: [10., 10., 10.]
    kappa1_s: [1., 1., 1.]

    alpha_c: [ 0.5, 0.5, 0.5]
    beta1_c: [ 1., 1., 1. ]
    beta2_c: [ 1., 1., 1. ]
    beta3_c: [ 1., 1., 1. ]
    Tc: [ 10., 10., 10. ]
    kappa1_c: [1., 1., 1.]

    k2: [1.5, 1.5, 2]
#    alpha_s: [0.846153846, 0.846153846, 0.846153846]
#    beta1_s: [5., 5., 5.]
#    beta2_s: [1., 1., 1.]
#    beta3_s: [1., 1., 1.]
#    Ts: [5., 5., 5.]
#    kappa1_s: [1.1, 1.1, 1.1]
#
#    alpha_c: [0.846153846, 0.846153846, 0.846153846]
#    beta1_c: [7., 7., 7.]
#    beta2_c: [1., 1., 1.]
#    beta3_c: [1., 1., 1.]
#    Tc: [10., 10., 10.]
#    kappa1_c: [0.81, 0.81, 0.81]
#
#    k2: [4., 4., 4.]

    k_yyf_i: [0.0, 0.0, 0.0]
    k_yyf_d: [0., 0., 0.]
    k_yyf_p: [0., 0., 0.0]
    k_com_pos: [0.0, 0.0, 0.0]
    k_com_vel: [0.0, 0.0, 0.]
    k_com_acc: [0.0, 0.0, 0.0]

    dim: 3
    dt: 0.01

uav2_pdt_do:
    T0: [5, 5, 5]
    k1: [1, 1, 1]
    alpha: [0.5, 0.5, 0.5]
    beta1: [1, 1, 1]
    beta2: [1, 1, 1]
    beta3: [1, 1, 1]
    dim: 3
    dt: 0.01

uav2_obs_xy:
    use_freq: True
    omega: [[1.0, 1.1, 1.2], [1.0, 1.1, 1.2]]
    dim: 2
    dt: 0.01

uav2_obs_z:
    use_freq: True
    omega: [[1.2, 1.2, 1.2]]
    dim: 1
    dt: 0.01
