# waiting time
t_miemie: 5.0

# group number
test_group: 0

# sampling time
dt: 0.01

# max time
time_max: 30.0

use_gazebo: true
use_obs: true

controller: 'FNTSMC'
# CONTROLLER = 'RL'
# CONTROLLER = 'PX4-PID'
# CONTROLLER = 'MPC'