t_miemie: 5
dt: 0.01
time_max: 30.0
use_gazebo: true
use_obs: true
uav_existance: [1, 1, 1, 1]

controller: 'FNTSMC'
pi: 3.141592653589793
# CONTROLLER = 'RL'
# CONTROLLER = 'PX4-PID'
# CONTROLLER = 'MPC'

test_group: 0
ra: [ 1.0, 1.0, 0.3, 0. ]
rp: [ 6, 6, 8, 10 ]
rba: [ 0, 0, 1, 0. ]
rbp: [ 1.5707963267948966, 0, 0, 0 ]

oa_0: [ 0., 0., 0. ]
op_0: [ 5, 5, 4 ]
oba_0: [ 1.0, 0, 0 ]
obp_0: [ 0., 0., 0. ]

oa_1: [ 0., 0., 0. ]
op_1: [ 5, 5, 4 ]
oba_1: [ 0.0, 1.0, 0 ]
obp_1: [ 0., 0., 0. ]

oa_2: [ 0., 0., 0. ]
op_2: [ 5, 5, 4 ]
oba_2: [ -1.0, 0, 0 ]
obp_2: [ 0., 0., 0. ]

oa_3: [ 0., 0., 0. ]
op_3: [ 5, 5, 4 ]
oba_3: [ 0.0, -1.0, 0 ]
obp_3: [ 0., 0., 0. ]
