t_miemie: 5
dt: 0.01
time_max: 30.0
use_gazebo: true
use_obs: true
uav_existance: [1, 1, 0, 0]

controller: 'FNTSMC'
pi: 3.1416
# CONTROLLER = 'RL'
# CONTROLLER = 'PX4-PID'
# CONTROLLER = 'MPC'

test_group: 0

trajectory_0:
  ra: [ 0.5, 0.5, 0.3, 0. ]
  rp: [ 6, 6, 8, 10 ]
  rba: [ 0, 0, 1, 0. ]
  rbp: [ 1.5708, 0, 0, 0 ]

  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[1.0, 0, 0], [0, 1.0, 0], [-1.0, 0., 0.], [0., -1.0, 0.]]
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]

trajectory_1:
  ra: [0, 0, 0, 0]
  rp: [6, 6, 8, 10]
  rba: [0, 0, 1.0, 0]
  rbp: [1.5708, 0, 0, 0]

  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[1.0, 0, 0], [0, 1.0, 0], [-1.0, 0., 0.], [0., -1.0, 0.]]
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]

trajectory_2:
  ra: [1, 1, 0.4, 0.0]
  rp: [10, 10, 8, 10]
  rba: [0, 0, 1.0, 0]
  rbp: [ 1.5708, 0, 0, 0 ]

  oa: [[1.0, 1.0, 0.], [1.0, 1.0, 0.], [1.0, 1.0, 0.], [1.0, 1.0, 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[0., 0., 0], [0., 0., 0], [0., 0., 0.], [0., 0., 0.]]
  obp: [[1.5708, 0., 0.], [3.1416, 1.5708, 0.], [-1.5708, 3.1416, 0.], [0., -1.5708, 0.]]

trajectory_3:
  ra: [1, 1, 0.5, 0.0]
  rp: [10, 10, 8, 10]
  rba: [0, 0, 1.0, 0]
  rbp: [0, 0, 0, 0 ]

  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[1.0, 0, 0], [0, 1.0, 0], [-1.0, 0., 0.], [0., -1.0, 0.]]
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]

trajectory_else:
  ra: [0, 0, 0, 0]
  rp: [10, 10, 8, 10]
  rba: [0, 0, 1.0, 0]
  rbp: [0, 0, 0, 0 ]

  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[1.0, 0, 0], [0, 1.0, 0], [-1.0, 0., 0.], [0., -1.0, 0.]]
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
