t_miemie: 0
dt: 0.01
time_max: 30.0
use_gazebo: true
use_obs: false
uav_existance: [1, 1, 1, 1]

gazebo_offset: [[3, 0, 0], [0, 3, 0], [-3, 0, 0], [0, -3, 0]]   # gazebo 的仿真模型中有一个初始的位置偏移
pi: 3.1416

controller: 'FNTSMC'
#controller: 'RL'
# controller: 'PX4-PID'
#controller: 'FT-PD'
# controller: 'PDT-FNTSMC'
# controller: 'RFNTSMC'

test_group: 0

trajectory_0:  # 编队 follow 下边的车，队形不变
  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]    # 振幅
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]                # 周期
  oba: [[2, 0, 2], [0, 2, 2], [-2, 0., 2], [0., -2, 2.]]            # 初始偏移
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]   # 相位

trajectory_1: # 编队 follow 下边的车，队形是 sin 变化
  oa: [[2, 2, 0], [2, 2, 0], [2, 2, 0], [2, 2, 0]]
  op: [[10, 10, 10], [10, 10, 10], [10, 10, 10], [10, 10, 10]]
  oba: [[0., 0., 1], [0., 0., 2], [0., 0., 1], [0., 0., 2]]
  obp: [[1.5708, 0., 0.], [3.1416, 1.5708, 0.], [-1.5708, 3.1416, 0.], [0., -1.5708, 0.]]

trajectory_else:
  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[1.0, 0, 1], [0, 1.0, 1], [-1.0, 0., 1.], [0., -1.0, 1.]]
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
