t_miemie: 5
dt: 0.01
time_max: 30.0
use_gazebo: true
use_obs: true
uav_existance: [1, 1, 1, 1]

pi: 3.1416

controller: 'FNTSMC'
#controller: 'RL'
# controller: 'PX4-PID'
# controller: 'FT-PD'
# controller: 'RFNTSMC'

test_group: 1

trajectory_0:
  ra: [1.0, 1.0, 0.3, 0.]
  rp: [6, 6, 8, 10]
  rba: [0, 0, 1, 0.]
  rbp: [1.5708, 0, 0, 0]

  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[1.0, 0, 0], [0, 1.0, 0], [-1.0, 0., 0.], [0., -1.0, 0.]]
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]

trajectory_1:   # 定点
  center: [[0.0, 0.0, 1.5, 0.0], [0.0, 0.0, 1.5, 0], [0, 0, 1.5, 0], [0, 0, 1.5, 0]]
  offset: [[[3.0, 0.0, 0.], [3.0, 3.0, 0.5], [-3.0, 3.0, 0.5], [3.0, 3.0, 0.5]],
           [[0.0, 3.0, 0.], [-3.0, 3.0, -0.5], [3.0, 3.0, -0.5], [-3.0, 3.0, -0.5]],
           [[-3.0, 0.0, -0.], [-3.0, -3.0, -0.5], [3.0, -3.0, -0.5], [-3.0, -3.0, -0.5]],
           [[0.0, -3.0, -0.], [3.0, -3.0, 0.5], [-3.0, -3.0, 0.5], [3.0, -3.0, 0.5]]]

trajectory_2:
  ra: [0, 0, 0., 0.0]
  rp: [10, 10, 8, 10]
  rba: [0, 0, 1.0, 0]
  rbp: [ 1.5708, 0, 0, 0 ]

  oa: [[1.3, 1.3, 0.], [1.3, 1.3, 0.], [1.3, 1.3, 0.], [1.3, 1.3, 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[0., 0., 0.7], [0., 0., -0.3], [0., 0., 0.7], [0., 0., -0.3]]
  obp: [[1.5708, 0., 0.], [3.1416, 1.5708, 0.], [-1.5708, 3.1416, 0.], [0., -1.5708, 0.]]

trajectory_3:
  ra: [3, 3, 0.2, 0.0]
  rp: [10, 10, 8, 10]
  rba: [0, 0, 1.0, 0]
  rbp: [0, 0, 0, 0 ]

  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[1.0, 0, 0], [0, 1.0, 0], [-1.0, 0., 0.], [0., -1.0, 0.]]
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]

trajectory_else:
  ra: [0, 0, 0, 0]
  rp: [10, 10, 8, 10]
  rba: [0, 0, 1.0, 0]
  rbp: [0, 0, 0, 0 ]

  oa: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
  op: [[5, 5, 4], [5, 5, 4], [5, 5, 4], [5, 5, 4]]
  oba: [[1.0, 0, 0], [0, 1.0, 0], [-1.0, 0., 0.], [0., -1.0, 0.]]
  obp: [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]
